# Generated by Django 4.1.7 on 2023-03-06 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='about',
        ),
        migrations.AddField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('689357c4-6c97-4e5c-9705-a7e09c243bff'), editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='last_Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='phoneNumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='photo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='registrationDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
