# Generated by Django 4.1.7 on 2023-03-06 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_newuser_about_newuser_documentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('c8db4997-5a4c-4c15-a323-943782528711'), editable=False, null=True, unique=True),
        ),
    ]
