# Generated by Django 4.1.7 on 2023-03-06 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_documentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('39f09acd-a60e-4ac1-8497-28b59cacfb66'), editable=False, null=True, unique=True),
        ),
    ]
