# Generated by Django 4.1.7 on 2023-03-06 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_newuser_documentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('0dcbd255-fb69-478c-badf-867efd0c1d46'), editable=False, null=True, unique=True),
        ),
    ]
