# Generated by Django 4.1.7 on 2023-03-06 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_newuser_start_date_alter_newuser_documentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('c2a313f4-6dcf-4170-88a4-382a4d7c0bed'), editable=False, null=True, unique=True),
        ),
    ]
