# Generated by Django 4.1.7 on 2023-03-06 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_newuser_documentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('abb079e6-19e2-4859-b11b-8157e63695e4'), editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
