# Generated by Django 4.1.7 on 2023-03-06 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_newuser_documentid_alter_newuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('c19232e1-bb76-4a12-84b5-6295eef88a95'), editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
