# Generated by Django 4.1.7 on 2023-03-06 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_newuser_documentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('a3e1d1a2-37b5-4e62-8c44-b19d8c3463d5'), editable=False, null=True, unique=True),
        ),
    ]
