# Generated by Django 4.1.7 on 2023-03-06 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_newuser_documentid_alter_newuser_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='photo',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('95780a40-3794-430a-91f9-a4ca37ae3f9a'), editable=False, null=True, unique=True),
        ),
    ]
