# Generated by Django 4.1.7 on 2023-03-06 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_newuser_gender_remove_newuser_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('69226d3c-865b-44e6-a62a-e71a6b059015'), editable=False, null=True, unique=True),
        ),
    ]
