# Generated by Django 4.1.7 on 2023-03-06 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_newuser_documentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='last_Name',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('f25eca06-ac34-456a-982a-b9bc38cf6b77'), editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
