# Generated by Django 4.1.7 on 2023-03-06 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_newuser_documentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_Name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('52a2ff12-a6d8-4400-aabc-3db927ff0e01'), editable=False, null=True, unique=True),
        ),
    ]
