# Generated by Django 4.1.7 on 2023-03-06 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_last_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('62447387-cb87-44a6-9363-56a74bfaf84d'), editable=False, null=True, unique=True),
        ),
    ]
