# Generated by Django 4.1.7 on 2023-03-06 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_newuser_documentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('b4144751-c0b6-4ea1-8acf-236110ec92e7'), editable=False, null=True, unique=True),
        ),
    ]
