# Generated by Django 4.1.7 on 2023-03-06 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_newuser_is_verified_userprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('17d66dc3-93b6-497c-b286-2780170728f7'), editable=False, null=True, unique=True),
        ),
    ]
