# Generated by Django 4.1.7 on 2023-03-06 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_newuser_documentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('a1ffc387-e042-4fcf-9504-d12749f53f97'), editable=False, null=True, unique=True),
        ),
    ]
