# Generated by Django 4.1.7 on 2023-03-06 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_newuser_documentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('429d2a89-3ea0-4036-9009-091b22ce46d3'), editable=False, null=True, unique=True),
        ),
    ]
