# Generated by Django 4.1.7 on 2023-03-06 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_newuser_documentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('5c3188fc-2e21-4f8c-a28f-c7087faee181'), editable=False, null=True, unique=True),
        ),
    ]
