# Generated by Django 4.1.7 on 2023-03-06 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_userprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('3699a198-c968-40f4-8374-345f9adf56dc'), editable=False, null=True, unique=True),
        ),
    ]
