# Generated by Django 4.1.7 on 2023-03-06 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_newuser_documentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('4fd1001d-42eb-4858-b5f9-859a831845bd'), null=True, unique=True),
        ),
    ]
