# Generated by Django 4.1.7 on 2023-03-07 00:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_newuser_documentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('c094c419-b5eb-476e-942f-8a7b3077987b'), null=True, unique=True),
        ),
    ]
