# Generated by Django 4.1.7 on 2023-03-07 01:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_newuser_documentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='documentId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('cde3740d-7c5b-43dd-acd9-175f1c8da196'), null=True, unique=True),
        ),
    ]
