# Generated by Django 4.1.7 on 2023-03-07 03:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_userprofile_documentid_alter_newuser_documentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('df07ba72-15e2-502f-8415-47b546add3cb')),
        ),
    ]
