# Generated by Django 4.1.7 on 2023-03-07 03:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_newuser_documentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='documentId',
            field=models.UUIDField(default=uuid.UUID('94be7678-df61-446c-8ae5-9e7d6f7361f9'), unique=True),
        ),
    ]
